# -*- coding: utf-8 -*-
"""car_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiRElCUuwEB8H7wbrrmLKRu-rCIE66Fu
"""

!pip install ultralytics
from ultralytics import YOLO
import cv2



!pip install yt-dlp



import cv2
from ultralytics import YOLO
from google.colab.patches import cv2_imshow
import collections

# 1. Modeli ve Videoyu Yükle
model = YOLO("yolo11m.pt")
video_path = "video_dosyam.mp4"
cap = cv2.VideoCapture(video_path)

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))

# Çıktı Videosu
out = cv2.VideoWriter("islenmis_video.mp4", cv2.VideoWriter_fourcc(*"mp4v"), fps, (width, height))

# Sayaçlar ve Takip Listeleri
track_history = []
total_car_counts = collections.defaultdict(set) # Benzersiz ID'leri tutmak için
class_names = model.model.names # Sınıf isimlerini al (car, truck, bus vb.)

while cap.isOpened():
    success, frame = cap.read()
    if not success:
        break

    # Sadece araç sınıflarını takip et (2: araba, 3: motorsiklet, 5: otobüs, 7: kamyon)
    results = model.track(frame, persist=True, classes=[2, 3, 5, 7], verbose=False)

    if results[0].boxes.id is not None:
        boxes = results[0].boxes.xyxy.cpu()
        track_ids = results[0].boxes.id.int().cpu().tolist()
        clss = results[0].boxes.cls.int().cpu().tolist()

        for track_id, cls in zip(track_ids, clss):
            # Her bir sınıf (model tipi) için benzersiz ID'yi set içine ekle
            obj_name = class_names[cls]
            total_car_counts[obj_name].add(track_id)

    # Görsel üzerine toplam sayıları yazdır
    annotated_frame = results[0].plot()
    y_offset = 30
    for obj_name, ids in total_car_counts.items():
        text = f"Toplam {obj_name}: {len(ids)}"
        cv2.putText(annotated_frame, text, (20, y_offset), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)
        y_offset += 30

    out.write(annotated_frame)

# 2. Kaynakları Serbest Bırak
cap.release()
out.release()

# 3. Sonuçları Bir Metin Dosyasına Kaydet
with open("araba_sayilari.txt", "w", encoding="utf-8") as f:
    f.write("--- VIDEO ANALIZ SONUCLARI ---\n")
    toplam_hepsi = 0
    for obj_name, ids in total_car_counts.items():
        sayi = len(ids)
        toplam_hepsi += sayi
        f.write(f"{obj_name}: {sayi} adet\n")
    f.write(f"\nGENEL TOPLAM ARAC: {toplam_hepsi}")

print("İşlem tamamlandı! 'islenmis_video.mp4' ve 'araba_sayilari.txt' dosyalarını kontrol edebilirsin.")

import yt_dlp

video_url = 'https://www.youtube.com/watch?v=FWQ9huLmekg'

ydl_opts = {
    # En iyi kaliteyi tek bir mp4 dosyasında birleştirir
    'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
    # Dosya ismini 'video_dosyam.mp4' olarak sabitliyoruz
    'outtmpl': 'video_dosyam.mp4',
    # Eğer dosya zaten varsa üzerine yazar
    'overwrites': True,
}

try:
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([video_url])
    print("İndirme başarıyla tamamlandı: video_dosyam.mp4")
except Exception as e:
    print(f"Bir hata oluştu: {e}")