# -*- coding: utf-8 -*-
"""falcon_nesne_tespiti_modeli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2MnYDXwq5LrWJCZrMGdwyYQhvylUeQp
"""

!pip install ultralytics

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive/projeler/Model_test_eğitimi/goog_colab

from ultralytics import YOLO
model=YOLO("yolo11s.pt")

conf_path="/content/drive/MyDrive/projeler/Model_test_eğitimi/goog_colab/falcon_model.pt"

from ultralytics import YOLO

model=YOLO(conf_path)
sonuclar = model.predict("test3.jpg", save=True)
sonuclar[0].show()

#sonuçlar=model.train(
#    data=conf_path,
 #   epochs=50,
#    batch=16,
 #   imgsz=640

#)

# 1. Gerekli kütüphaneyi içe aktarın
!pip install yt-dlp
from ultralytics import YOLO

# 2. Model yolunuzu tanımlayın (Kendi eğittiğiniz Falcon modeliniz)
conf_path = "/content/drive/MyDrive/projeler/Model_test_eğitimi/goog_colab/falcon_model.pt"

# 3. Modeli yükleyin
model = YOLO(conf_path)

# 4. YouTube linki üzerinden tahmini başlatın
# Not: YOLOv8 doğrudan YouTube URL'lerini destekler.
video_url = "https://youtu.be/Z4TXCZG_NEY"

# 'save=True' ile tespit yapılmış videoyu kaydedebilirsiniz.
# 'conf=0.25' güven eşiğidir, ihtiyaca göre değiştirebilirsiniz.
sonuclar = model.predict(source=video_url, save=True, conf=0.25)

print("İşlem tamamlandı. Sonuçlar 'runs/detect/predict' klasörüne kaydedildi.")

import os
from ultralytics import YOLO

# 1. Videoyu yt-dlp ile en iyi kalitede 'video.mp4' olarak indir
video_url = "https://youtu.be/Z4TXCZG_NEY"
!yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4" {video_url} -o "falcon_video.mp4"

# 2. Modelinizi yükleyin
conf_path = "/content/drive/MyDrive/projeler/Model_test_eğitimi/goog_colab/falcon_model.pt"
model = YOLO(conf_path)

# 3. İndirilen yerel dosya üzerinden tespiti başlatın
# Bu video Falcon 9'un fırlatılışını ve
# iniş bacaklarının açılması gibi kritik anları içerir.
if os.path.exists("falcon_video.mp4"):
    sonuclar = model.predict(source="falcon_video.mp4", save=True, conf=0.25)
    print("Başarıyla tamamlandı! Sonuçlar 'runs/detect/predict' klasöründe.")
else:
    print("Video indirilemedi, lütfen linki kontrol edin.")

from ultralytics import YOLO
import os

# 1. Model yolunu belirle
conf_path = "/content/drive/MyDrive/projeler/Model_test_eğitimi/goog_colab/falcon_model.pt"

# 2. Modeli yükle
model = YOLO(conf_path)

# 3. Yerel video dosyası üzerinden tespiti başlat
# Dosya yolunu senin belirttiğin gibi '/content/falcon_video.mp4' olarak ayarladım
video_path = "/content/falcon_video.mp4"

if os.path.exists(video_path):
    # save=True: Sonucu kaydeder
    # project ve name parametreleri ile kayıt yerini sabitleyelim ki bulması kolay olsun
    results = model.predict(source=video_path, save=True, conf=0.25, project="deneyler", name="falcon_test")

    # Kaydedilen dosyanın tam yolunu yazdıralım
    print(f"\nİşlem başarıyla tamamlandı!")
    print(f"Tespit yapılmış video şu klasörde: /content/deneyler/falcon_test/")
else:
    print(f"Hata: {video_path} yolunda video bulunamadı. Lütfen dosya adını kontrol et.")

from ultralytics import YOLO
import cv2

# 1. Modeli ve Videoyu Tanımla
conf_path = "/content/drive/MyDrive/projeler/Model_test_eğitimi/goog_colab/falcon_model.pt"
model = YOLO(conf_path)
video_path = "/content/falcon_video.mp4"
output_path = "/content/falcon_islenmis.mp4"

# 2. Tahmin ve Kayıt İşlemi
# vid_stride=2 ekleyerek her 2 karede bir işlem yapıp hızı artırabiliriz
results = model.predict(source=video_path, save=True, conf=0.25, name="falcon_yeni", project="deneyler")

# Kayıt klasörünü zorla kontrol et
import os
print("\nOluşan dosyalar:")
!ls -R /content/deneyler/

import cv2
from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/projeler/Model_test_eğitimi/goog_colab/falcon_model.pt")
cap = cv2.VideoCapture("/content/falcon_video.mp4")

# Video özelliklerini al
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))

# Çıktı videosu için hazırlık
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('/content/kesin_sonuc.mp4', fourcc, fps, (width, height))

print("Video işleniyor, lütfen bekleyin...")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Her karede nesne tespiti yap
    results = model(frame, verbose=False)

    # Tespitleri kare üzerine çiz
    annotated_frame = results[0].plot()

    # Kareyi yeni videoya yaz
    out.write(annotated_frame)

cap.release()
out.release()
print("İşlem bitti! Dosya: /content/kesin_sonuc.mp4")